Vagrant.configure(2) do |config|

  config.vm.box = "box-cutter/ubuntu1404-desktop"

  config.vm.box_check_update = false 

  config.vm.provider "virtualbox" do |vb| 

    vb.gui = true  

    vb.memory = "2048"
  
    vb.name = "FSE-2010-Basset2"

  end


  config.vm.provision "shell", inline: <<-SHELL

    sudo add-apt-repository -y ppa:webupd8team/java

    sudo apt-get update

    echo "oracle-java6-installer shared/accepted-oracle-license-v1-1 select true" | sudo debconf-set-selections

    sudo apt-get install -y oracle-java6-installer

    sudo apt-get install oracle-java6-set-default

    export JAVA_HOME=/usr/lib/jvm/java-6-oracle

    sudo apt-get install -y ant 
   
    source /etc/environment

    cd Desktop

    wget /home/vagrant/Desktop/jpf.tar.gz https://github.com/SoftwareEngineeringToolDemos/FSE-2010-Basset/raw/master/build-vm/vm-contents/jpf.tar.gz 

    tar -zxvf jpf.tar.gz

    rm jpf.tar.gz

    mkdir /home/vagrant/.jpf

    cp /home/vagrant/Desktop/jpf/site.properties /home/vagrant/.jpf

    cd /home/vagrant/Desktop/jpf/jpf-core

    ant

    cd /home/vagrant/Desktop/jpf/jpf-actor

    ant

    cd /home/vagrant/Desktop
    
    chown -R vagrant: jpf


    # Remove unused icons from sidebar (making VM as minimal as possible)
    rm -f "/usr/share/applications/ubuntu-amazon-default.desktop"
    rm -f "/usr/share/applications/libreoffice-calc.desktop"
    rm -f "/usr/share/applications/libreoffice-writer.desktop"
    rm -f "/usr/share/applications/libreoffice-impress.desktop"
    rm -f "/usr/share/applications/ubuntu-software-center.desktop"
    update-desktop-database

    mkdir "/home/vagrant/.config/autostart"
    mkdir "/home/vagrant/scripts"

     # Disable screen lock
  
    wget -O "/home/vagrant/scripts/screenlock.sh" https://github.com/SoftwareEngineeringToolDemos/FSE-2013-aPET/raw/master/build-vm/vm-contents/screenlock.sh
  
    wget -O "/home/vagrant/.config/autostart/screenlock.desktop" https://github.com/SoftwareEngineeringToolDemos/FSE-2013-aPET/raw/master/build-vm/vm-contents/screenlock.desktop
  
    chmod -R a+rwx "/home/vagrant/scripts/"

    cd /home/vagrant/Desktop

    wget -O "desktop_folder.tar.gz" https://github.com/SoftwareEngineeringToolDemos/FSE-2010-Basset/raw/master/build-vm/vm-contents/desktop_folder.tar.gz 

    tar -xvzf desktop_folder.tar.gz

    rm desktop_folder.tar.gz 

    mv Basset.desktop /home/vagrant/.config/autostart/

    update-desktop-database
  
    reboot
   
  SHELL

end


# bin/jpf gov.nasa.jpf.actor.Basset pi.Driver 3