Vagrant.configure(2) do |config|

   config.vm.box = "box-cutter/ubuntu1404-desktop"

   config.vm.box_check_update = false 

   config.vm.provider "virtualbox" do |vb| 

     vb.gui = true  

     vb.memory = "2048"
  
     vb.name = "FSE-2010-Basset"

   end


   config.vm.provision "shell", inline: <<-SHELL

   sudo add-apt-repository -y ppa:webupd8team/java

   sudo apt-get update

   echo "oracle-java6-installer shared/accepted-oracle-license-v1-1 select true" | sudo debconf-set-selections

   sudo apt-get install -y oracle-java6-installer

   sudo apt-get install oracle-java6-set-default

   export JAVA_HOME=/usr/lib/jvm/java-6-oracle

   source /etc/environment

   cd Desktop

    wget /home/haris/Desktop/jpf.tar.gz https://github.com/hmansari/FSE-2010-Basset/raw/master/build-vm/vm-contents/jpf.tar.gz

    tar -zxvf jpf.tar.gz

    rm jpf.tar.gz

   chown -R vagrant: jpf
   SHELL

end
